spring:
  application:
    name: api-mcp-client
  main:
    web-application-type: none
  ai:
    mcp:
      client:
        enabled: true
        name: api-mcp-client
        type: SYNC
        sse:
          connections:
            api-mcp-server-localhost:
              url: "http://localhost:8765/"
#            api-mcp-server-127001:
#              url: "http://127.0.0.1:8765/"
        version: 1.0.0
logging:
  level:
    root: off